/*
 * Copyright (C) 2019 Android Ice Cold Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/* Do not touch! Auto-generated by bash*/

package com.aicp.extras.search;

import com.aicp.extras.R;

/* Do not touch! Auto-generated by bash*/
public class AeFragmentList {

    public static class AeFragmentInfo {
        public final String fragmentClass;
        public final String key;
        public final int title;
        public final int summary;
        public final int xmlRes;
        public AeFragmentInfo(String fragmentClass, String key, int title, int summary, int xmlRes) {
            this.fragmentClass = fragmentClass;
            this.key = key;
            this.title = title;
            this.summary = summary;
            this.xmlRes = xmlRes;
        }
    }

    /* Do not touch! Auto-generated by bash*/
    public static final AeFragmentInfo[] FRAGMENT_LIST = {
        new AeFragmentInfo("com.aicp.extras.fragments.About", "about", R.string.about_title, 0, R.xml.about),
        new AeFragmentInfo("com.aicp.extras.fragments.AeSettings", "ae_settings", R.string.ae_settings_title, 0, R.xml.ae_settings),
        new AeFragmentInfo("com.aicp.extras.fragments.AmbientEdgeLights", "ambient_edge_lights", R.string.edge_light_enable_title, 0, R.xml.ambient_edge_lights),
        new AeFragmentInfo("com.aicp.extras.fragments.AmbientMediaTicker", "ambient_media_ticker", R.string.force_ambient_for_media_pref_title, 0, R.xml.ambient_media_ticker),
        new AeFragmentInfo("com.aicp.extras.fragments.BatteryBar", "battery_bar", R.string.battery_bar_title, 0, R.xml.battery_bar),
        new AeFragmentInfo("com.aicp.extras.fragments.Dashboard", "dashboard", R.string.app_name, 0, R.xml.dashboard),
        new AeFragmentInfo("com.aicp.extras.fragments.HeadsUpOptions", "heads_up_options", R.string.notification_heads_up_title, 0, R.xml.heads_up_options),
        new AeFragmentInfo("com.aicp.extras.fragments.Lockscreen", "lockscreen", R.string.lockscreen_title, 0, R.xml.lockscreen),
        new AeFragmentInfo("com.aicp.extras.fragments.LogIt", "log_it", R.string.log_it_title, 0, R.xml.log_it),
        new AeFragmentInfo("com.aicp.extras.fragments.OtherUi", "other_ui", R.string.other_ui_title, 0, R.xml.other_ui),
        new AeFragmentInfo("com.aicp.extras.fragments.PulseSettings", "pulse_settings", R.string.pulse_settings, 0, R.xml.pulse_settings),
        new AeFragmentInfo("com.aicp.extras.fragments.QuickSettings", "quick_settings", R.string.quick_settings_title, 0, R.xml.quick_settings),
        new AeFragmentInfo("com.aicp.extras.fragments.SlimRecentAppSidebar", "slim_recent_app_sidebar", R.string.recent_app_sidebar_title, 0, R.xml.slim_recent_app_sidebar),
        new AeFragmentInfo("com.aicp.extras.fragments.SlimRecentAppSidebarStyle", "slim_recent_app_sidebar_style", R.string.recent_app_sidebar_title, 0, R.xml.slim_recent_app_sidebar_style),
        new AeFragmentInfo("com.aicp.extras.fragments.SlimRecents", "slim_recents", R.string.slim_recents_title, 0, R.xml.slim_recents),
        new AeFragmentInfo("com.aicp.extras.fragments.SlimRecentsBlacklist", "slim_recents_blacklist", R.string.slim_blacklist_apps_cat_title, 0, R.xml.slim_recents_blacklist),
        new AeFragmentInfo("com.aicp.extras.fragments.SmartPixels", "smart_pixels", R.string.smart_pixels_title, 0, R.xml.smart_pixels),
        new AeFragmentInfo("com.aicp.extras.fragments.Spoofing", "", R.string.spoofing_title, 0, R.xml.spoofing),
        new AeFragmentInfo("com.aicp.extras.fragments.StatusBar", "status_bar", R.string.status_bar_title, 0, R.xml.status_bar),
        new AeFragmentInfo("com.aicp.extras.fragments.StatusBarClockSettings", "status_bar_clock", R.string.status_bar_clock_title, 0, R.xml.status_bar_clock),
        new AeFragmentInfo("com.aicp.extras.fragments.StatusBarLogo", "status_bar_logo", R.string.status_bar_logo_title, 0, R.xml.status_bar_logo_settings),
        new AeFragmentInfo("com.aicp.extras.fragments.SystemBehaviour", "system_behaviour", R.string.system_behaviour_title, 0, R.xml.system_behaviour),
        new AeFragmentInfo("com.aicp.extras.fragments.Weather", "weather", R.string.weather_title, 0, R.xml.weather),
    };
}
